### ISSUE TITLE
setup `Github Pages` as staging server

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#1]
`Github` has one cute feature called `Github Pages` it can turn you repo, in our case https://github.com/IlyaRucavitcyn/vanga.by into a real site, for more information please check this out. https://help.github.com/categories/github-pages-basics/ 

We have to setup our repository properly and use `production` ready code to present current state of development by `Github Pages` feature

**Comment by IlyaRucavitcyn** [comment]
@shemerey somehow it happend the issue is done ^)
https://github.com/IlyaRucavitcyn/vanga.by

**Comment by shemerey** [comment]
LGTM, closign
