### ISSUE TITLE
fix currency icon 

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#10]
When you change window size some artefacts apear, It's better to use icon as one single vector image, If you can't create it by your one plz ask `Jane` too provide it in correct format 

<img width="813" alt="icon" src="https://cloud.githubusercontent.com/assets/31591/11590114/13ef3fc4-9a9f-11e5-9618-88676cad4b92.png">

**Comment by IlyaRucavitcyn** [comment]
bug fixet by using svg images

**Comment by shemerey** [comment]
fixed
