### ISSUE TITLE
setup dev server 

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#21]
For correct development process we need to separate development env from production env.

In development mode we need to run server `express` based with will server our html pages as well as generated js and css files `plz take into account we don't need to minimize in dev mode`

In production mode we should be able to build the whole site and deliver it (deploy)

**Comment by shemerey** [comment]
Plz setup development server it should be able to 

- [ ] serve static html file such as index.html
- [ ] serve generated bundle.css & js file 
- [ ] watch changes in css or js files and regenerate it on fly 

You can find more here 
* https://truongtx.me/2014/03/14/automate-javascript-development-with-gulp/
* http://laravel.io/forum/04-03-2014-how-to-handle-development-and-production-assets-with-gulp 
* https://www.npmjs.com/package/gulp-watch

**Comment by IlyaRucavitcyn** [comment]
[Here](https://github.com/IlyaRucavitcyn/vanga.by/tree/devenvserver) plz check at your computer how it all works before me pulling the request.

**Comment by shemerey** [comment]
LGTM :shipit:
