### ISSUE TITLE
Setup background video

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#23]
* Be default you have to place background [video](https://github.com/IlyaRucavitcyn/vanga.by/blob/design/design/vanga.mp4) 
* User should be able to `pause` / `start` video by clicking on (I) button at left bottom cornet

**Comment by IlyaRucavitcyn** [comment]
Please check my pull request accirding to that issue [here](https://github.com/IlyaRucavitcyn/vanga.by/pull/26)

**Comment by shemerey** [comment]
well done bro
