### ISSUE TITLE
Chart / Stats page 

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#24]
based on Landing page we should implement following [stats page](https://github.com/IlyaRucavitcyn/vanga.by/blob/design/design/Second%20page%20with%20graph.png)

**Comment by IlyaRucavitcyn** [comment]
The link above is broken, could you check?

**Comment by shemerey** [comment]
You have to use `http://www.highcharts.com/demo` to implement chart area

**Comment by IlyaRucavitcyn** [comment]
Look through my [pull request](https://github.com/IlyaRucavitcyn/vanga.by/pull/27), plz.

**Comment by shemerey** [comment]
LGTM, just squash all commits in this branch and we good to go

**Comment by shemerey** [comment]
done
