### ISSUE TITLE
Add jasmine as Test framework for project

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#29]
- [ ] add http://jasmine.github.io/2.0/node.html
- [ ] create first simple test 
 - [ ] It should check whether `/` return `http ok 200` or not

**Comment by shemerey** [comment]
BTW plz. take into account it has to be executable by `npm test`

**Comment by IlyaRucavitcyn** [comment]
Please find my [pull request](https://github.com/IlyaRucavitcyn/vanga.by/pull/30) for that issue.

**Comment by shemerey** [comment]
done
