### ISSUE TITLE
Fix a few bugs with layout

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#3]
Here is a few bugs with design 

- [x] background has wrong size, or overlay plz check this out
- [x] Currency icons have to be vector based, you can use plain `svg` objects or create icon font, and use it as storage for all icons.

If you are not familiar with `Icon Font` technic plz check this out http://fontello.com/ 
you can find plenty of resources about this approach. e.g. https://www.elegantthemes.com/blog/resources/how-to-use-and-embed-an-icon-font-on-your-website  

<img width="1472" alt="ilyarucavitcyn_github_io_vanga_by_" src="https://cloud.githubusercontent.com/assets/31591/11465147/4a58f006-9747-11e5-8009-590e3e859aaa.png">

**Comment by IlyaRucavitcyn** [comment]
Concerning background this is the prtscr how psd looks in photoshop from my side.
![psd_view](https://cloud.githubusercontent.com/assets/14336732/11465382/4f0d1f08-9749-11e5-8375-8d367c5f6954.png)
If the overlay should cover all the screenspace I will fix it.

**Comment by shemerey** [comment]
:cry: something wrong with `psd`

**Comment by IlyaRucavitcyn** [comment]
PSD is one of the main difficulties of the project, to tell the truth :)

**Comment by IlyaRucavitcyn** [comment]
Background positioning is fixed.
Icon Fonts are connected, it is only up to their styling
