### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#33]
Now we should think about persisting data, plz setup `mongodb` locally and try it out. 

http://cwbuecheler.com/web/tutorials/2013/node-express-mongo/

plz complete this tutorial and, and after it create `API` endpoint to:

* save user `prediction` in database
* get all predictions for particular currency

This issue will be completed when application will be able handle all actions above + will be covered by specs

**Comment by IlyaRucavitcyn** [comment]
Please find the latest version [here](https://github.com/IlyaRucavitcyn/vanga.by/pull/34).

**Comment by shemerey** [comment]
done
