### ISSUE TITLE
use placeholder for main currency input 

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#4]
We have to use `placeholder` for example data on a main currency input

<img width="843" alt="screenshot_12_3_15__6_04_pm" src="https://cloud.githubusercontent.com/assets/31591/11564106/5d6d4cd4-99e8-11e5-817e-f54275dabd0f.png">

For additional information about `placeholder` you can read here, it looks like HTML5 has build in placeholder support, plz use `HTML5` polyfill where it possible 
* https://mathiasbynens.github.io/jquery-placeholder/
* http://habrahabr.ru/post/74363/

**Comment by IlyaRucavitcyn** [comment]
Placeholder added
