### ISSUE TITLE
Setup dev env

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#6]
I think now is a perfect time to setup a proper dev `env`

you have to install 
* [x] [node js](https://nodejs.org/en/) (with [npm](https://www.npmjs.com/)) 
* [x] run `npm init` like `git init` but for creating a package from the current repo
* [x] install [gulp](http://gulpjs.com/) (as a task manager)
* [x] add linter for css (https://www.npmjs.com/package/gulp-csslint)

As result you should be able run 

     $ gulp lint
 
and get the result for css lint,  it will prevent you from doing mistakes in a future

**Comment by shemerey** [comment]
As final result your should be able to clone you project, run 

```bash
$ npm i 
```
And be ready for development

**Comment by IlyaRucavitcyn** [comment]
All the packages and plugins are installed and ready for the next step.

**Comment by shemerey** [comment]
done
