### ISSUE TITLE
About panel (burger icon control)

### ISSUE THREAD

**Issue by shemerey** [IlyaRucavitcyn/vanga.by#8]
On the up right hand side corner user can click on the `burger` icon, User should be able to see overlay panel with additional informations, for example plz check `belzen.by`

**Comment by shemerey** [comment]
<img width="757" alt="burger icon" src="https://cloud.githubusercontent.com/assets/31591/11590213/bef238fe-9a9f-11e5-8fe0-5cd01ee993a7.png">

**Comment by IlyaRucavitcyn** [comment]
For that issue I need to know the exact design of the additional information or I can create smth like at belzen.by . We also have "i" button at the bottom left corner of psd. What is the functional for that?

**Comment by shemerey** [comment]
@IlyaRucavitcyn yes plz create empty right hand side panel with white background. On click `( i )` we need to open modal window. but It's gonna be another issue don't think about it for now

**Comment by IlyaRucavitcyn** [comment]
Completed. Clean white sidebar appears after pushing burger icon. to hide it - click on the sidebar.

**Comment by IlyaRucavitcyn** [comment]
Completed. Clean white sidebar appears after pushing burger icon. to hide it - click on the sidebar.

**Comment by shemerey** [comment]
done
